iesgestionweb/app/iesgestionweb/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import RedirectView

urlpatterns = [
    re_path(r'^$', RedirectView.as_view(url='incidencias/', permanent=False), name='index'),
    path('incidencias/', include('incidencias.urls')),
    path('admin/', admin.site.urls),
]

iesgestionweb/app/incidencias/urls.py
from django.urls import path, re_path

from . import views

app_name = 'incidencias' # Para espacio de nombres url... 'incidencias:index'
                         # https://docs.djangoproject.com/en/3.2/intro/tutorial03/#namespacing-url-names

urlpatterns = [
    # ex: /polls/
    #re_path(r'^incidencia/(?:/(?P<lugar_id>\d+))?/?$', views.index, name='listado'),
    #path('', views.index, name='listado'),
    path('', views.IncidenciaListView.as_view(), name='listado'),
    path('nueva/', views.IncidenciaFormView.as_view(), name='nueva-incidencia'),
]
"""
# ex: /polls/5/
path('<int:question_id>/', views.detail, name='detail'),
# ex: /polls/5/results/
path('<int:question_id>/results/', views.results, name='results'),
# ex: /polls/5/vote/
path('<int:question_id>/vote/', views.vote, name='vote'),
"""

iesgestionweb/app/incidencias/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

class Acceso(models.Model):
    clave = models.CharField(max_length=200)
    fecha = models.DateTimeField('Desde')

    def __str__(self):
        return self.clave

class Lugar(models.Model):
    lugar = models.CharField(max_length=200)

    def __str__(self):
        return self.lugar

class Incidencia(models.Model):
    lugar = models.ForeignKey(Lugar, on_delete=models.CASCADE)
    texto = models.TextField(verbose_name='problema')
    ESTADOS = [
        ('A', 'Abierta'),
        ('C', 'Cerrada'),
    ]
    estado = models.CharField(
        max_length=2,
        choices=ESTADOS,
        default='A',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.lugar.__str__() + ' ' + self.get_estado_display() + ' ' + timezone.localtime(self.created_at).strftime('%Y-%m-%d %H:%M')

class Respuesta(models.Model):
    incidencia = models.ForeignKey(Incidencia, on_delete=models.CASCADE, related_name='respuestas', verbose_name='respuestas')
    texto = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.incidencia.__str__() + ' - Respuesta ' + timezone.localtime(self.updated_at).strftime('%Y-%m-%d %H:%M')

iesgestionweb/app/incidencias/forms.py
from django import forms
from .models import Lugar, Acceso, Incidencia

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_pass(value):
    actual = Acceso.objects.latest('fecha')
    if value != actual.clave:
        raise ValidationError(
            'La contraseña ' + value + ' no es correcta',
            params={'value': value},
        )

class IncidenciaForm(forms.ModelForm):
    secreto = forms.CharField(label='Contraseña',
                    widget=forms.PasswordInput(attrs={'placeholder': 'Secreto...'}),
                    validators=[validate_pass]
            )

    class Meta:
        model = Incidencia
        fields = ['lugar', 'texto']
        labels = {
            'lugar': 'Aula',
            'texto': 'Texto',
            'secreto': 'Contraseña'
        }

iesgestionweb/app/incidencias/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from .models import Lugar, Incidencia, Respuesta, Acceso
from .tables import IncidenciaTable, IncidenciaFilter
from .forms import IncidenciaForm
from django_tables2.views import SingleTableView

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.views.generic.edit import FormView

from django.urls import reverse

class IncidenciaListView(SingleTableMixin, FilterView):

    table_class = IncidenciaTable
    queryset = Incidencia.objects.all().order_by('-created_at')
    template_name = 'incidencias/index.html'
    filterset_class = IncidenciaFilter

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)

        try:
            lugar_id = int(self.request.GET.get('lugar', ''))
            lugar = Lugar.objects.get(pk=lugar_id)
            self.queryset = self.queryset.filter(lugar__pk=lugar_id)
        except:
            lugar_id = 0

        context['lugares'] = Lugar.objects.all()

        return context


class IncidenciaFormView(FormView):
    template_name = 'incidencias/incidencia.html'
    form_class = IncidenciaForm

    def get_success_url(self):
        return reverse('incidencias:listado')+"?lugar="+str(self.return_lugar.id)

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        form.save()

        self.return_lugar = form.cleaned_data.get('lugar')

        return super().form_valid(form)

iesgestionweb/app/iesgestionweb/templates/base.html
{# Load the tag library #}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Gestión incidencias Jorge Dueñas Lerín{% endblock %}</title>
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

    <style>
      .form-incidencias label {
        text-align: right;
      }

      .form-incidencias button {
        text-align: center;
      }
    </style>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
      $(document).ready(function() {
          $('#id_lugar').select2();
      });
    </script>
  </head>
  <body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

iesgestionweb/app/iesgestionweb/templates/bootstrap5.html
{% load django_tables2 %}
{% load i18n %}
{% block table-wrapper %}
<div class="table-container">
    {% block table %}
        <table {% render_attrs table.attrs class="table" %}>
            {% block table.thead %}
            {% if table.show_header %}
                <thead {{ table.attrs.thead.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <th {{ column.attrs.th.as_html }}>
                        {% if column.orderable %}
                            <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                        {% else %}
                            {{ column.header }}
                        {% endif %}
                    </th>
                {% endfor %}
                </tr>
                </thead>
            {% endif %}
            {% endblock table.thead %}
            {% block table.tbody %}
                <tbody {{ table.attrs.tbody.as_html }}>
                {% for row in table.paginated_rows %}
                    {% block table.tbody.row %}
                    <tr {{ row.attrs.as_html }}>
                        {% for column, cell in row.items %}
                            <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                        {% endfor %}
                    </tr>
                    {% endblock table.tbody.row %}
                {% empty %}
                    {% if table.empty_text %}
                    {% block table.tbody.empty_text %}
                        <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                    {% endblock table.tbody.empty_text %}
                    {% endif %}
                {% endfor %}
                </tbody>
            {% endblock table.tbody %}
            {% block table.tfoot %}
            {% if table.has_footer %}
            <tfoot {{ table.attrs.tfoot.as_html }}>
                <tr>
                {% for column in table.columns %}
                    <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                {% endfor %}
                </tr>
            </tfoot>
            {% endif %}
            {% endblock table.tfoot %}
        </table>
    {% endblock table %}

    {% block pagination %}
        {% if table.page and table.paginator.num_pages > 1 %}
        <nav aria-label="Table navigation">
            <ul class="pagination justify-content-center">
            {% if table.page.has_previous %}
                {% block pagination.previous %}
                <li class="previous page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                        {% trans 'previous' %}
                    </a>
                </li>
                {% endblock pagination.previous %}
            {% endif %}
            {% if table.page.has_previous or table.page.has_next %}
            {% block pagination.range %}
            {% for p in table.page|table_page_range:table.paginator %}
                <li class="page-item{% if table.page.number == p %} active{% endif %}">
                    <a class="page-link" {% if p != '...' %}href="{% querystring table.prefixed_page_field=p %}"{% endif %}>
                        {{ p }}
                    </a>
                </li>
            {% endfor %}
            {% endblock pagination.range %}
            {% endif %}
            {% if table.page.has_next %}
                {% block pagination.next %}
                <li class="next page-item">
                    <a href="{% querystring table.prefixed_page_field=table.page.next_page_number %}" class="page-link">
                        {% trans 'next' %}
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endblock pagination.next %}
            {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endblock pagination %}
</div>
{% endblock table-wrapper %}

iesgestionweb/app/incidencias/templates/incidencias/incidencia.html
{% extends "base.html" %}
{% load bootstrap5 %}

{% block title %}Gestión incidencias Jorge Dueñas Lerín{% endblock %}

{% block content %}
<h1>Sistema de gestión de incidencias</h1>
<h2>Alta de incidencia</h2>

{% bootstrap_form_errors form %}

<form action="#" method="post" class="form form-incidencias">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' horizontal_label_class='col-md-1'%}

    <div class="mb-3 row">
      <label class="col-md-3 col-form-label" for="id_texto"></label>
      <div class="col-md-9">{% bootstrap_button 'Crear incidencia' %}</div>
    </div>

</form>

{% endblock %}

iesgestionweb/app/incidencias/templates/incidencias/index.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}

{% block title %}Gestión incidencias Jorge Dueñas Lerín{% endblock %}

{% block content %}
<h1>Sistema de gestión de incidencias</h1>

<!---
<form class="row g-3" action="/" id="formSeleccionLugar">
  <div class="form-floating">
    <select class="form-select" id="floatingLugar" name="lugar">
      <option value="">Todos</option>
      {% for lugar in lugares %}
         <option value="{{ lugar.id }}"
             {% if lugar.id == lugar_selected.id %}selected="selected"{% endif %}>
             {{lugar.lugar|capfirst}}
         </option>
      {% endfor %}
    </select>
    <label for="floatingLugar">Selecciona aula</label>
  </div>
  <div class="">
    <button type="submit" class="btn btn-primary col">Ver incidencias</button>
  </div>

</form>
--->
{% if filter %}
    <form action="" method="get" class="form form-incidencias">
      <div class="form-floating">
        {% bootstrap_form filter.form layout='horizontal' horizontal_label_class='col-md-1' %}

        <div class="mb-1 row">
          <label class="col-md-1 col-form-label" for="id_texto"></label>
          <div class="col-md-11">
            {% bootstrap_button 'Ver incidencias' %}
            <a type="button" class="btn btn-success" href={% url 'incidencias:nueva-incidencia' %}>
              Nueva incidencia
            </a>
          </div>
        </div>
      </div>
    </form>

{% endif %}

{% render_table table %}
{% endblock %}